version: "3.8"
services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=db_user
      - DB_PASSWORD=pwd123
      - DB_NAME=shop
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: "postgres:13"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
      - POSTGRES_DB=shop
#      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U db_user -d shop'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - /Users/alexanderkucher/shop/db/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge